class DosDateTime {
  const DosDateTime._();

  /// This is usually in the PE File Header
  static DateTime fromTimestamp(int dateTimeStamp) =>
      DateTime.fromMillisecondsSinceEpoch(dateTimeStamp * 1000, isUtc: true);

  /// This is usually in the ZIP Central Directory and related places.
  static DateTime fromInt(int date, int time) {
    if (date > 0xffff) {
      throw FormatException("Date should be a max 0xffff", date);
    }
    if (time > 0xffff) {
      throw FormatException("Time should be a max 0xffff", time);
    }

    // The bitshifting code below was generated by Claude.
    // It does have tests verifying that the beahviour is consistent with the actual Win32 API in `dos_date_time_test.dart`.
    int secs = (time & 0x1F) * 2;
    int mins = (time >> 5) & 0x3F;
    int hrs = (time >> 11) & 0x1F;

    int day = date & 0x1F;
    int mth = (date >> 5) & 0x0F;
    int yrs = 1980 + ((date >> 9) & 0x7F);

    return DateTime(yrs, mth, day, hrs, mins, secs);
  }
}
