name: file_metadata
description: A package to get metadata for various file types.
version: 0.0.1
repository: https://github.com/BoseVJeff/file_metadata

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  cross_file: ^0.3.4+1
  mime: ^1.0.5
  path: ^1.9.0
  # path: ^1.8.0

dev_dependencies:
  coverage: ^1.8.0
  lints: ^3.0.0
  test: ^1.24.0
